name: Deploy MoonTV to SAP Cloud Foundry

on:
  workflow_dispatch:
    inputs:
      region:
        description: "选择部署区域"
        required: true
        default: "SG(free)"
        type: choice
        options:
          - 'SG(free)'
          - 'US(free)'
          - 'AWS-AU(Sydney)'
          - 'AWS-BR(São Paulo)'
          - 'AWS-KR(Seoul)'
          - 'AWS-CA(Montreal)'
          - 'AWS-US(VA)'
          - 'AWS-US(OR)'
          - 'AWS-EU(Frankfurt)'
          - 'AWS-JP(Tokyo)'
          - 'AWS-SG(Singapore)'
          - 'GCP-AU(Sydney)'
          - 'GCP-BR(São Paulo)'
          - 'GCP-US(IA)'
          - 'GCP-EU(Frankfurt)'
          - 'GCP-JP(Osaka)'
          - 'GCP-JP(Tokyo)'
          - 'GCP-IL(Tel Aviv)'
          - 'GCP-IN(Mumbai)'
          - 'GCP-KSA(Dammam)'
          - 'Azure-AU(Sydney)'
          - 'Azure-BR(São Paulo)'
          - 'Azure-CA(Montreal)'
          - 'Azure-US(VA)'
          - 'Azure-US(WA)'
          - 'Azure-EU(Netherlands)'
          - 'Azure-JP(Tokyo)'
          - 'Azure-SG(Singapore)'
          - 'Neo-UAE(Dubai)'
          - 'Neo-KSA(Riyadh)'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set API endpoint and APP name
        run: |
          RANDOM_STR=$(head /dev/urandom | tr -dc 'a-z' | head -c 6)
          case "${{ github.event.inputs.region }}" in
            "SG(free)")
              echo "CF_API=https://api.cf.ap21.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-freesg$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "US(free)")
              echo "CF_API=https://api.cf.us10-001.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-freeus$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "AWS-AU(Sydney)")
              echo "CF_API=https://api.cf.ap10.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-awsau$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "AWS-BR(São Paulo)")
              echo "CF_API=https://api.cf.br10.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-awsbr$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "AWS-KR(Seoul)")
              echo "CF_API=https://api.cf.ap12.hana.ondemand.com" >> $GITHUB_ENV
              echo
