name: Deploy MoonTV to SAP Cloud Foundry

on:
  workflow_dispatch:
    inputs:
      region:
        description: "选择部署区域"
        required: true
        default: "SG(free)"
        type: choice
        options:
          - 'SG(free)'
          - 'US(free)'
          - 'AWS-AU(Sydney)'
          - 'AWS-BR(São Paulo)'
          - 'AWS-KR(Seoul)'
          - 'AWS-CA(Montreal)'
          - 'AWS-US(VA)'
          - 'AWS-US(OR)'
          - 'AWS-EU(Frankfurt)'
          - 'AWS-JP(Tokyo)'
          - 'AWS-SG(Singapore)'
          - 'GCP-AU(Sydney)'
          - 'GCP-BR(São Paulo)'
          - 'GCP-US(IA)'
          - 'GCP-EU(Frankfurt)'
          - 'GCP-JP(Osaka)'
          - 'GCP-JP(Tokyo)'
          - 'GCP-IL(Tel Aviv)'
          - 'GCP-IN(Mumbai)'
          - 'GCP-KSA(Dammam)'
          - 'Azure-AU(Sydney)'
          - 'Azure-BR(São Paulo)'
          - 'Azure-CA(Montreal)'
          - 'Azure-US(VA)'
          - 'Azure-US(WA)'
          - 'Azure-EU(Netherlands)'
          - 'Azure-JP(Tokyo)'
          - 'Azure-SG(Singapore)'
          - 'Neo-UAE(Dubai)'
          - 'Neo-KSA(Riyadh)'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set API endpoint and APP name
        run: |
          RANDOM_STR=$(head /dev/urandom | tr -dc 'a-z' | head -c 6)
          case "${{ github.event.inputs.region }}" in
            "SG(free)")
              echo "CF_API=https://api.cf.ap21.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-freesg$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "US(free)")
              echo "CF_API=https://api.cf.us10-001.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-freeus$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "AWS-AU(Sydney)")
              echo "CF_API=https://api.cf.ap10.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-awsau$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "AWS-BR(São Paulo)")
              echo "CF_API=https://api.cf.br10.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-awsbr$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "AWS-KR(Seoul)")
              echo "CF_API=https://api.cf.ap12.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-awskr$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "AWS-CA(Montreal)")
              echo "CF_API=https://api.cf.ca10.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-awsca$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "AWS-US(VA)")
              echo "CF_API=https://api.cf.us10-001.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-awsusva$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "AWS-US(OR)")
              echo "CF_API=https://api.cf.us11.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-awsusor$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "AWS-EU(Frankfurt)")
              echo "CF_API=https://api.cf.eu10-005.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-waseu$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "AWS-JP(Tokyo)")
              echo "CF_API=https://api.cf.jp10.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-awsjp$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "AWS-SG(Singapore)")
              echo "CF_API=https://api.cf.ap11.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-awssg$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "GCP-AU(Sydney)")
              echo "CF_API=https://api.cf.ap30.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-gcpau$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "GCP-BR(São Paulo)")
              echo "CF_API=https://api.cf.br30.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-gcpbr$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "GCP-US(IA)")
              echo "CF_API=https://api.cf.us30.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-gcpus$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "GCP-EU(Frankfurt)")
              echo "CF_API=https://api.cf.eu30.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-gcpeu$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "GCP-JP(Osaka)")
              echo "CF_API=https://api.cf.jp30.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-gcpjpo$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "GCP-JP(Tokyo)")
              echo "CF_API=https://api.cf.jp31.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-gcpjpt$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "GCP-IL(Tel Aviv)")
              echo "CF_API=https://api.cf.il30.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-gcpil$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "GCP-IN(Mumbai)")
              echo "CF_API=https://api.cf.in30.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-gcpin$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "GCP-KSA(Dammam)")
              echo "CF_API=https://api.cf.sa31.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-gcpsa$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "Azure-AU(Sydney)")
              echo "CF_API=https://api.cf.ap20.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-azau$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "Azure-BR(São Paulo)")
              echo "CF_API=https://api.cf.br20.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-azbr$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "Azure-CA(Montreal)")
              echo "CF_API=https://api.cf.ca20.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-azca$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "Azure-US(VA)")
              echo "CF_API=https://api.cf.us21.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-azva$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "Azure-US(WA)")
              echo "CF_API=https://api.cf.us20.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-azwa$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "Azure-EU(Netherlands)")
              echo "CF_API=https://api.cf.eu20-001.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-azeu$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "Azure-JP(Tokyo)")
              echo "CF_API=https://api.cf.jp20.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_NAME=moontv-azjp$RANDOM_STR" >> $GITHUB_ENV
              ;;
            "Azure-SG(Singapore)")
              echo "CF_API=https://api.cf.ap21.hana.ondemand.com" >> $GITHUB_ENV
              echo "APP_
